version: '3'
services:
  app:
    build: .
    working_dir: /opt/app/ll-admin
    volumes:
      - .:/opt/app/ll-admin/
      - /opt/app/ll-admin/node_modules
    ports:
      - "3000:8080"
    entrypoint: ["npm"]
    command: ["start"]